NguyenQuangNamK22CNTT2/Models/hoasi.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenQuangNamK22CNTT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoasi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoasi()
        {
            this.sanphams = new HashSet<sanpham>();
        }
    
        public int hoasi_id { get; set; }
        public string hoasi_name { get; set; }
        public string bio { get; set; }
        public string website { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}

NguyenQuangNamK22CNTT2/Controllers/hoasisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NguyenQuangNamK22CNTT2.Models;

namespace NguyenQuangNamK22CNTT2.Controllers
{
    public class hoasisController : Controller
    {
        private NguyenQuangNamK22CNTT2Entities db = new NguyenQuangNamK22CNTT2Entities();

        // GET: hoasis
        public ActionResult Index()
        {
            return View(db.hoasis.ToList());
        }

        // GET: hoasis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            hoasi hoasi = db.hoasis.Find(id);
            if (hoasi == null)
            {
                return HttpNotFound();
            }
            return View(hoasi);
        }

        // GET: hoasis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: hoasis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "hoasi_id,hoasi_name,bio,website,ImagePath")] hoasi hoasi)
        {
            if (ModelState.IsValid)
            {
                db.hoasis.Add(hoasi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hoasi);
        }

        // GET: hoasis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            hoasi hoasi = db.hoasis.Find(id);
            if (hoasi == null)
            {
                return HttpNotFound();
            }
            return View(hoasi);
        }

        // POST: hoasis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "hoasi_id,hoasi_name,bio,website,ImagePath")] hoasi hoasi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hoasi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hoasi);
        }

        // GET: hoasis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            hoasi hoasi = db.hoasis.Find(id);
            if (hoasi == null)
            {
                return HttpNotFound();
            }
            return View(hoasi);
        }

        // POST: hoasis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            hoasi hoasi = db.hoasis.Find(id);
            db.hoasis.Remove(hoasi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NguyenQuangNamK22CNTT2/Views/hoasis/Create.cshtml
@model NguyenQuangNamK22CNTT2.Models.hoasi

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>hoasi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.hoasi_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hoasi_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hoasi_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hoasi_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hoasi_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hoasi_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NguyenQuangNamK22CNTT2/Views/hoasis/Delete.cshtml
@model NguyenQuangNamK22CNTT2.Models.hoasi
<link href="~/Scripts/del.css" rel="stylesheet" />
@{
    ViewBag.Title = "Xác nhận xóa";
}

<h2 class="text-center">Xác nhận xóa tác giả</h2>

<h3 class="text-center text-danger">Bạn có chắc chắn muốn xóa hoạ sĩ này không?</h3>

<div class="delete-container">
    <h4>Thông tin hoạ sĩ</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Tên Hoạ Sĩ:</dt>
        <dd>@Html.DisplayFor(model => model.hoasi_name)</dd>

        <dt>Tiểu Sử</dt>
        <dd>@Html.DisplayFor(model => model.bio)</dd>

        <dt>Website</dt>
        <dd>@Html.DisplayFor(model => model.website)</dd>

        <dt>Ảnh</dt>
        <dd>@Html.DisplayFor(model => model.ImagePath)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions">
            <button type="submit" class="btn btn-danger">Xóa</button>
            @Html.ActionLink("Quay lại danh sách", "Index", new { @class = "btn btn-secondary" })
        </div>
    }
</div>

NguyenQuangNamK22CNTT2/Views/hoasis/Details.cshtml
@model NguyenQuangNamK22CNTT2.Models.hoasi

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>hoasi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.hoasi_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hoasi_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.hoasi_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NguyenQuangNamK22CNTT2/Views/hoasis/Edit.cshtml
@model NguyenQuangNamK22CNTT2.Models.hoasi

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>hoasi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.hoasi_id)

        <div class="form-group">
            @Html.LabelFor(model => model.hoasi_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hoasi_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hoasi_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NguyenQuangNamK22CNTT2/Views/hoasis/Index.cshtml
@model IEnumerable<NguyenQuangNamK22CNTT2.Models.hoasi>
<link href="~/Scripts/all.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
}

<h2>Tiểu sử thông tin của các hoạ sĩ</h2>
<div class="table-container">
    <table class="table table-hover">
        <thead class="thead-light">
            <tr>
                <th>Tên Hoạ Sĩ</th>
                <th>Chân dung</th>
                <th>Tiểu Sử</th>
                <th>Hành Động</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.hoasi_name)</td>
                    <td><img src="~/images/@item.ImagePath" alt="anh" style="width:100px; height:auto;" /></td>
                    <td>@Html.DisplayFor(modelItem => item.bio)</td>
                    <td>
                        @Html.ActionLink("Sửa", "Edit", new { id = item.hoasi_id }, new { @class = "btn btn-warning btn-sm" })
                        @Html.ActionLink("Xoá", "Delete", new { id = item.hoasi_id }, new { @class = "btn btn-danger btn-sm" })
                        @Html.ActionLink("Chi tiết", "Details", new { id = item.hoasi_id }, new { @class = "btn btn-info btn-sm" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p>
        @Html.ActionLink("Thêm mới", "Create", "hoasis", new { @class = "btn-add-new" })
    </p>



</div>