NguyenQuangNamK22CNTT2/Models/giohang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenQuangNamK22CNTT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giohang
    {
        public int giohang_id { get; set; }
        public Nullable<int> khachhang_id { get; set; }
        public Nullable<int> tranhve_id { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual khachhang khachhang { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}

NguyenQuangNamK22CNTT2/Controllers/giohangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NguyenQuangNamK22CNTT2.Models;

namespace NguyenQuangNamK22CNTT2.Controllers
{
    public class giohangsController : Controller
    {
        private NguyenQuangNamK22CNTT2Entities db = new NguyenQuangNamK22CNTT2Entities();

        // GET: giohangs
        public ActionResult Index()
        {
            var giohangs = db.giohangs.Include(g => g.khachhang).Include(g => g.sanpham);
            return View(giohangs.ToList());
        }

        // GET: giohangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            giohang giohang = db.giohangs.Find(id);
            if (giohang == null)
            {
                return HttpNotFound();
            }
            return View(giohang);
        }

        // GET: giohangs/Create
        public ActionResult Create()
        {
            ViewBag.khachhang_id = new SelectList(db.khachhangs, "khachhang_id", "khachhang_name");
            ViewBag.tranhve_id = new SelectList(db.sanphams, "tranhve_id", "tieude");
            return View();
        }

        // POST: giohangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "giohang_id,khachhang_id,tranhve_id,soluong")] giohang giohang)
        {
            if (ModelState.IsValid)
            {
                db.giohangs.Add(giohang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.khachhang_id = new SelectList(db.khachhangs, "khachhang_id", "khachhang_name", giohang.khachhang_id);
            ViewBag.tranhve_id = new SelectList(db.sanphams, "tranhve_id", "tieude", giohang.tranhve_id);
            return View(giohang);
        }

        // GET: giohangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            giohang giohang = db.giohangs.Find(id);
            if (giohang == null)
            {
                return HttpNotFound();
            }
            ViewBag.khachhang_id = new SelectList(db.khachhangs, "khachhang_id", "khachhang_name", giohang.khachhang_id);
            ViewBag.tranhve_id = new SelectList(db.sanphams, "tranhve_id", "tieude", giohang.tranhve_id);
            return View(giohang);
        }

        // POST: giohangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "giohang_id,khachhang_id,tranhve_id,soluong")] giohang giohang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(giohang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.khachhang_id = new SelectList(db.khachhangs, "khachhang_id", "khachhang_name", giohang.khachhang_id);
            ViewBag.tranhve_id = new SelectList(db.sanphams, "tranhve_id", "tieude", giohang.tranhve_id);
            return View(giohang);
        }

        // GET: giohangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            giohang giohang = db.giohangs.Find(id);
            if (giohang == null)
            {
                return HttpNotFound();
            }
            return View(giohang);
        }

        // POST: giohangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            giohang giohang = db.giohangs.Find(id);
            db.giohangs.Remove(giohang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NguyenQuangNamK22CNTT2/Views/giohangs/Create.cshtml
@model NguyenQuangNamK22CNTT2.Models.giohang

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>giohang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.giohang_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giohang_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giohang_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.khachhang_id, "khachhang_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("khachhang_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.khachhang_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tranhve_id, "tranhve_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("tranhve_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tranhve_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soluong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NguyenQuangNamK22CNTT2/Views/giohangs/Delete.cshtml
@model NguyenQuangNamK22CNTT2.Models.giohang

@{
    ViewBag.Title = "Xác nhận xóa giỏ hàng";
}

<h2 class="text-center">Xác nhận xóa giỏ hàng</h2>

<h3 class="text-center text-danger">Bạn có chắc chắn muốn xóa giỏ hàng này không?</h3>

<div class="delete-container">
    <h4>Thông tin giỏ hàng</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Khách hàng</dt>
        <dd>@Html.DisplayFor(model => model.khachhang_id)</dd>

        <dt>Sản phẩm</dt>
        <dd>@Html.DisplayFor(model => model.tranhve_id)</dd>

        <dt>Số lương</dt>
        <dd>@Html.DisplayFor(model => model.soluong)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions">
            <button type="submit" class="btn btn-danger">Xóa</button>
            @Html.ActionLink("Quay lại danh sách", "Index", new { @class = "btn btn-secondary" })
        </div>
    }
</div>

NguyenQuangNamK22CNTT2/Views/giohangs/Details.cshtml
@model NguyenQuangNamK22CNTT2.Models.giohang

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>giohang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.khachhang.khachhang_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.khachhang.khachhang_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sanpham.tieude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sanpham.tieude)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.giohang_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NguyenQuangNamK22CNTT2/Views/giohangs/Edit.cshtml
@model NguyenQuangNamK22CNTT2.Models.giohang

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>giohang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.giohang_id)

        <div class="form-group">
            @Html.LabelFor(model => model.khachhang_id, "khachhang_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("khachhang_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.khachhang_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tranhve_id, "tranhve_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("tranhve_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tranhve_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soluong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NguyenQuangNamK22CNTT2/Views/giohangs/Index.cshtml
@model IEnumerable<NguyenQuangNamK22CNTT2.Models.giohang>
<link href="~/Scripts/all.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
}

<h2>Giỏ hàng</h2>
<div class="table-container">
    <table class="table table-hover">
        <thead class="thead-light">
            <tr>
                <th>
                    Số lượng
                </th>
                <th>
                    Tên Người Mua
                </th>
                <th>
                    Mã Sản Phẩm
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.soluong)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.khachhang.khachhang_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.sanpham.tieude)
                    </td>
                    <td>
                        @Html.ActionLink("Sửa", "Edit", new { id = item.giohang_id }, new { @class = "btn btn-warning btn-sm" })
                        @Html.ActionLink("Xoá", "Delete", new { id = item.giohang_id }, new { @class = "btn btn-danger btn-sm" })
                        @Html.ActionLink("Chi tiết", "Details", new { id = item.giohang_id }, new { @class = "btn btn-info btn-sm" })
                    </td>
                </tr>
            }

        </tbody>
    </table>
    <p>
        @Html.ActionLink("Create New", "Create", "giohangs", new { @class = "btn-add-new" })
    </p>
</div>