NguyenQuangNamK22CNTT2/Models/donhang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenQuangNamK22CNTT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donhang()
        {
            this.ctdonhangs = new HashSet<ctdonhang>();
        }
    
        public int donhang_id { get; set; }
        public Nullable<int> khachhang_id { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public Nullable<decimal> tong { get; set; }
        public string trangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdonhang> ctdonhangs { get; set; }
        public virtual khachhang khachhang { get; set; }
    }
}

NguyenQuangNamK22CNTT2/Controllers/donhangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NguyenQuangNamK22CNTT2.Models;

namespace NguyenQuangNamK22CNTT2.Controllers
{
    public class donhangsController : Controller
    {
        private NguyenQuangNamK22CNTT2Entities db = new NguyenQuangNamK22CNTT2Entities();

        // GET: donhangs
        public ActionResult Index()
        {
            var donhangs = db.donhangs.Include(d => d.khachhang);
            return View(donhangs.ToList());
        }

        // GET: donhangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            donhang donhang = db.donhangs.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(donhang);
        }

        // GET: donhangs/Create
        public ActionResult Create()
        {
            ViewBag.khachhang_id = new SelectList(db.khachhangs, "khachhang_id", "khachhang_name");
            return View();
        }

        // POST: donhangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "donhang_id,khachhang_id,ngay,tong,trangthai")] donhang donhang)
        {
            if (ModelState.IsValid)
            {
                db.donhangs.Add(donhang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.khachhang_id = new SelectList(db.khachhangs, "khachhang_id", "khachhang_name", donhang.khachhang_id);
            return View(donhang);
        }

        // GET: donhangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            donhang donhang = db.donhangs.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            ViewBag.khachhang_id = new SelectList(db.khachhangs, "khachhang_id", "khachhang_name", donhang.khachhang_id);
            return View(donhang);
        }

        // POST: donhangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "donhang_id,khachhang_id,ngay,tong,trangthai")] donhang donhang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donhang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.khachhang_id = new SelectList(db.khachhangs, "khachhang_id", "khachhang_name", donhang.khachhang_id);
            return View(donhang);
        }

        // GET: donhangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            donhang donhang = db.donhangs.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(donhang);
        }

        // POST: donhangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            donhang donhang = db.donhangs.Find(id);
            db.donhangs.Remove(donhang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NguyenQuangNamK22CNTT2/Views/donhangs/Create.cshtml
@model NguyenQuangNamK22CNTT2.Models.donhang

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>donhang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.donhang_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donhang_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donhang_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.khachhang_id, "khachhang_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("khachhang_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.khachhang_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.trangthai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.trangthai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.trangthai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NguyenQuangNamK22CNTT2/Views/donhangs/Delete.cshtml
@model NguyenQuangNamK22CNTT2.Models.donhang
<link href="~/Scripts/del.css" rel="stylesheet" />

@{
    ViewBag.Title = "Xác nhận xóa đơn hàng";
}

<h2 class="text-center">Xác nhận xóa đơn hàng</h2>

<h3 class="text-center text-danger">Bạn có chắc chắn muốn xóa đơn hàng này không?</h3>

<div class="delete-container">
    <h4>Thông tin đơn hàng</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Ngày Đặt</dt>
        <dd>@Html.DisplayFor(model => model.ngay)</dd>

        <dt>Tổng Tiền</dt>
        <dd>@Html.DisplayFor(model => model.tong)</dd>

        <dt>Trạng Thái</dt>
        <dd>@Html.DisplayFor(model => model.trangthai)</dd>

        <dt>Khách Hàng</dt>
        <dd>@Html.DisplayFor(model => model.khachhang.khachhang_name)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions">
            <button type="submit" class="btn btn-danger">Xóa</button>
            @Html.ActionLink("Quay lại danh sách", "Index", new { @class = "btn btn-secondary" })
        </div>
    }
</div>

NguyenQuangNamK22CNTT2/Views/donhangs/Details.cshtml
@model NguyenQuangNamK22CNTT2.Models.donhang

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>donhang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ngay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.trangthai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trangthai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.khachhang.khachhang_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.khachhang.khachhang_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.donhang_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NguyenQuangNamK22CNTT2/Views/donhangs/Edit.cshtml
@model NguyenQuangNamK22CNTT2.Models.donhang

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>donhang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.donhang_id)

        <div class="form-group">
            @Html.LabelFor(model => model.khachhang_id, "khachhang_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("khachhang_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.khachhang_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.trangthai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.trangthai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.trangthai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NguyenQuangNamK22CNTT2/Views/donhangs/Index.cshtml
@model IEnumerable<NguyenQuangNamK22CNTT2.Models.donhang>
<link href="~/Scripts/all.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
}

<h2>Chi tiết đơn hàng</h2>
<div class="table-container">
    <table class="table table-hover">
        <thead class="thead-light">
            <tr>
                <th>
                    Ngày đặt
                </th>
                <th>
                    Tổng
                </th>
                <th>
                    Trạng thái
                </th>
                <th>
                    Tên Người Mua
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ngay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tong)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.trangthai)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.khachhang.khachhang_name)
                    </td>
                    <td>
                        @Html.ActionLink("Sửa", "Edit", new { id = item.donhang_id }, new { @class = "btn btn-warning btn-sm" })
                        @Html.ActionLink("Xoá", "Delete", new { id = item.donhang_id }, new { @class = "btn btn-danger btn-sm" })
                        @Html.ActionLink("Thông Tin", "Details", new { id = item.donhang_id }, new { @class = "btn btn-info btn-sm" })
                    </td>
                </tr>
            }

        </tbody>
    </table>
    <p>
        @Html.ActionLink("Create New", "Create", "donhangs", new { @class = "btn-add-new" })
    </p>
</div>